// Jenkinsfile to scan RailsGoat with Brakeman
// Set up a Jenkins job against the source repo with file:///vagrant

pipeline {
  agent any
  
  stages {
    stage('build') {
      steps {
        // Check out source code into the workspace, initializing RailsGoat submodule
        checkout scmGit(
          branches: [[name: '*/main']],
          extensions:
            [submodule(recursiveSubmodules: true, reference: '')],
            userRemoteConfigs: [[url: 'file:///vagrant']]
        )
        sh 'docker-compose --file $WORKSPACE/sec-tests/brakeman/compose.yaml build'
      }
    }

    stage('brakeman-scan') {
      steps {
        // Run brakeman against RailsGoat submodule, output results to workspace
        sh 'docker-compose --file $WORKSPACE/sec-tests/brakeman/compose.yaml up brakeman-railsgoat-scan'
      }
    }
  }
  
  post {
    always {
      archiveArtifacts artifacts: 'railsgoat_brakeman_report.html', fingerprint: true
    }
  } 
}
