// Jenkinsfile to scan RailsGoat with Brakeman
// Set up a Jenkins job against the source repo with file:///vagrant

pipeline {
  agent any
  
  stages {
    stage('build') {
      steps {
        // Check out source code into the workspace
        checkout scm
        
        // Build the Brakeman container
        sh 'docker build -t brakeman:$BUILD_TAG $WORKSPACE/sec-tests/brakeman'
        
        // Run brakeman against RailsGoat submodule, output results to workspace
        sh 'set +e; docker run -v $WORKSPACE:/brakeman_vol brakeman:$BUILD_TAG brakeman -a -f html -o /brakeman_vol/railsgoat_brakeman_report.html $WORKSPACE/railsgoat; if [ "$?" -eq "3" ]; then exit 0; else exit 1; fi'
      }
    }
  }
  
  post {
    always {
      archiveArtifacts artifacts: 'railsgoat_brakeman_report.html', fingerprint: true
    }
  } 
}
