---
- name: Install RailsGoat lab prereqs
  become: true
  apt:
    state: present
    pkg:
      - tmux
      - git
      - curl
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - default-jre-headless
      - htop
      - tree

- name: Allow file:// URLs with git (used in the lab for using repo via vagrant://)
  become: true
  template:
    src: templates/gitconfig
    dest: /etc/gitconfig
