services:
  semgrep-railsgoat-scan:
    image: returntocorp/semgrep
    volumes:
      - ../../railsgoat/app:/src  # Railsgoat source code
      - ../..:/workspace          # For saving report
    command: semgrep
                --config auto
                --text
                --output /workspace/railsgoat_semgrep_results.txt
                /src
