// Jenkinsfile to scan RailsGoat with Semgrep

pipeline {
  agent any
  
  stages {
    stage('semgrep-scan') {
      steps {
        // Check out source code into the workspace, initializing RailsGoat submodule
        checkout scmGit(
          branches: [[name: '*/master']],
          extensions:
            [submodule(recursiveSubmodules: true, reference: '')],
            userRemoteConfigs: [[url: 'file:///vagrant']]
        )

        // Run semgrep against Railsgoat (text output)
        sh 'docker-compose --file $WORKSPACE/sec-tests/semgrep/compose.yaml up semgrep-railsgoat-scan'

        // Run semgrep against Railsgoat (SARIF output)
        sh 'docker-compose --file $WORKSPACE/sec-tests/semgrep/compose.yaml up semgrep-railsgoat-scan-sarif'
      }
    }
  }
  
  post {
    always {
      archiveArtifacts artifacts: 'railsgoat_semgrep_results.txt'
      archiveArtifacts artifacts: 'railsgoat_semgrep_results_sarif.json'
    }
  }
}
