// Jenkinsfile to scan RailsGoat with Semgrep

pipeline {
  agent any
  
  stages {
    stage('semgrep-scan') {
      steps {
        // Check out source code into the workspace, initializing RailsGoat submodule
        checkout scmGit(
          branches: [[name: '*/master']],
          extensions:
            [submodule(recursiveSubmodules: true, reference: '')],
            userRemoteConfigs: [[url: 'file:///vagrant']]
        )

        // Run semgrep against Railsgoat
        sh 'docker run -v $WORKSPACE/railsgoat/app:/src returntocorp/semgrep semgrep --metrics=off --text --config p/default /src > $WORKSPACE/railsgoat_semgrep_results.txt'
      }
    }
  }
  
  post {
    always {
      archiveArtifacts artifacts: 'railsgoat_semgrep_results.txt'
    }
  }
}
