/*
- Jenkinsfile for holding RailsGoat and ZAP open together (for one-off commands)
*/

pipeline {
  agent any
  
  stages {
    stage('build') {
      steps {
        // Check out source code into the workspace, initializing RailsGoat submodule
        checkout scmGit(
          branches: [[name: '*/main']],
          extensions:
            [submodule(recursiveSubmodules: true, reference: '')],
            userRemoteConfigs: [[url: 'file:///vagrant']]
        )

        // Build required containers
        sh 'docker-compose --file $WORKSPACE/sec-tests/hold-open/compose.yaml build'
      }
    }

    stage('hold-open') {
      steps {
        // Hold ZAP and RailsGoat open together
        sh 'docker-compose --file $WORKSPACE/sec-tests/hold-open/compose.yaml up zap-holdopen-with-railsgoat'
      }
    }
  }
  
  post {
    always {
      // Stop running containers
      sh 'docker-compose --file $WORKSPACE/sec-tests/hold-open/compose.yaml stop'
    }
  } 
}
