/*
- Jenkinsfile for scanning RailsGoat via OWASP ZAP
*/

pipeline {
  agent any
  
  stages {
    stage('build') {
      steps {
        // Check out source code into the workspace
        // checkout scm
        checkout scmGit(
          branches: [[name: '*/master']],
          extensions:
            [submodule(recursiveSubmodules: true, reference: '')],
            userRemoteConfigs: [[url: 'file:///vagrant']]
        )

        // Initialize RailsGoat submodule

        
        // Build RailsGoat container 
        // sh 'docker-compose -f $WORKSPACE/sec-tests/zap/compose.yaml build'
        // sh 'cd $WORKSPACE/sec-tests/zap && docker-compose build'
        
        // Run ZAP scan against RailsGoat
        sh 'cd $WORKSPACE/sec-tests/zap && docker-compose up --build zap-copy-report-to-workspace'
        // sh 'cd $WORKSPACE/sec-tests/zap && docker-compose run zap-scan'
      }
    }
  }
  
  post {
    always {
      // Archive the report with the build
      archiveArtifacts artifacts: 'railsgoat-zap-baseline.html', fingerprint: true

      // Delete the report from the workspace

      // Stop running containers
      sh 'cd $WORKSPACE/sec-tests/zap && docker-compose stop'
    }
  } 
}
