/*
- Jenkinsfile for scanning RailsGoat via ZAP's automation framework
*/

pipeline {
  agent any
  
  stages {
    stage('build') {
      steps {
        // Check out source code into the workspace, initializing RailsGoat submodule
        checkout scmGit(
          branches: [[name: '*/master']],
          extensions:
            [submodule(recursiveSubmodules: true, reference: '')],
            userRemoteConfigs: [[url: 'file:///vagrant']]
        )

        // Build required containers
        sh 'cd $WORKSPACE/sec-tests/zap-scan-automation-framework && docker-compose build'
      }
    }

    stage('test') {
      steps {
        // Run baseline ZAP scan against RailsGoat
        sh 'cd $WORKSPACE/sec-tests/zap-scan-automation-framework && docker-compose up zap-scan-automation-framework'
      }
    }
  }
  
  post {
    always {
      // Prepare ZAP report
      sh 'cd $WORKSPACE/sec-tests/zap-scan-automation-framework && docker-compose up zap-process-report'

      // Clean up containers (remove containers and volumes)
      sh 'cd $WORKSPACE/sec-tests/zap-scan-automation-framework && docker-compose down --volumes'
    }
  } 
}
