---
env:
  contexts:
  - name: "railsgoat"
    urls:
    - "http://railsgoat-web:3000/"
    includePaths:
    - "http://railsgoat-web:3000/*"
    excludePaths: []
    authentication:
      method: "browser"
      parameters:
        loginPageUrl: "http://railsgoat-web:3000"
        loginPageWait: 5
        browserId: "firefox-headless"
      verification:
        method: "autodetect"
    sessionManagement:
      method: "autodetect"
      parameters: {}
    users:
    - name: "ken"
      credentials:
        username: "ken@metacorp.com"
        password: "citrusblend"

jobs:
  - type: spider                       # The traditional spider - fast but doesnt handle modern apps so well
    parameters:
      context: railsgoat               # String: Name of the context to spider, default: first context
      user: ken                        # String: An optional user to use for authentication, must be defined in the env
      # url:                             # String: Url to start spidering from, default: first context URL
      maxDuration: 10                  # Int: The max time in minutes the spider will be allowed to run for, default: 0 unlimited
    tests:
      - name: 'Confirm railsgoat context is authenticated for traditional spider'
        type: stats
        statistic: 'stats.auth.configure.verification'
        operator: '=='
        value: 1
        onFail: 'error'
      - name: 'Confirm at least 1 successful authentication'
        type: stats
        statistic: 'stats.auth.success'
        operator: '>='
        value: 1
        onFail: 'error'
      - name: 'Confirm railsgoat context is using forms-based authentication'
        type: stats
        statistic: 'stats.auth.configure.auth.form'
        operator: '>='
        value: 1
        onFail: 'error'
  - type: spiderAjax
    parameters:
      context: railsgoat
      user: ken
      maxDuration: 20
  - type: activeScan                   # The active scanner - this actively attacks the target so should only be used with permission
    parameters:
      context: railsgoat               # String: Name of the context to attack, default: first context
      user: ken                        # String: An optional user to use for authentication, must be defined in the env
      # policy:                          # String: Name of the scan policy to be used, default: Default Policy
      # maxRuleDurationInMins:           # Int: The max time in minutes any individual rule will be allowed to run for, default: 0 unlimited
      maxScanDurationInMins: 20        # Int: The max time in minutes the active scanner will be allowed to run for, default: 0 unlimited
    tests:
      - name: 'Confirm railsgoat context is authenticated for active scan'
        type: stats
        statistic: 'stats.auth.configure.verification'
        operator: '=='
        value: 1
        onFail: 'error'
      - name: 'Confirm at least 1 successful authentication'
        type: stats
        statistic: 'stats.auth.success'
        operator: '>='
        value: 1
        onFail: 'error'
      - name: 'Confirm railsgoat context is using forms-based authentication'
        type: stats
        statistic: 'stats.auth.configure.auth.form'
        operator: '>='
        value: 1
        onFail: 'error'
  - type: report                       # Report generation
    parameters:
      # template:                         # String: The template id, default : modern
      # theme:                            # String: The template theme, default: the first theme defined for the template (if any)
      reportDir: /zap/wrk                 # String: The directory into which the report will be written
      reportFile: "{{yyyy-MM-dd HH:mm:ss}}-ZAP-Report-[[site]]"                         # String: The report file name pattern, default: {{yyyy-MM-dd}}-ZAP-Report-[[site]]
      reportTitle: RailsGoat Full Scan    # String: The report title
      reportDescription: Spider and scan RailsGoat
