/*
- Jenkinsfile for scanning RailsGoat via OWASP ZAP
*/

pipeline {
  agent any
  
  stages {
    stage('clean') {
      steps {
        // Clean workspace
        cleanWs()
      }
    }

    stage('build') {
      steps {
        // Check out source code into the workspace, initializing RailsGoat submodule
        checkout scmGit(
          branches: [[name: '*/master']],
          extensions:
            [submodule(recursiveSubmodules: true, reference: '')],
            userRemoteConfigs: [[url: 'file:///vagrant']]
        )

        // Build required containers
        sh 'cd $WORKSPACE/sec-tests/zap-baseline && docker-compose build'
      }
    }

    stage('test') {
      steps {
        // Run baseline ZAP scan against RailsGoat
        sh 'cd $WORKSPACE/sec-tests/zap-baseline && docker-compose up zap-scan-baseline'
      }
    }
  }
  
  post {
    always {
      // Copy the report from Docker volume to the workspace
      sh 'cd $WORKSPACE/sec-tests/zap-baseline && docker-compose up zap-copy-report-to-workspace'

      // Archive reports with the build
      archiveArtifacts artifacts: 'railsgoat-zap-baseline.html', fingerprint: true

      // Clean up containers (remove containers and volumes)
      sh 'cd $WORKSPACE/sec-tests/zap-baseline && docker-compose down --volumes'

      // Clean workspace
      // cleanWs()
    }
  } 
}
