/*
- Jenkinsfile for scanning RailsGoat via OWASP ZAP
*/

pipeline {
  agent any
  
  stages {
    stage('clean') {
      steps {
        // Clean workspace
        cleanWs()
      }
    }

    stage('build') {
      steps {
        // Check out source code into the workspace, initializing RailsGoat submodule
        checkout scmGit(
          branches: [[name: '*/main']],
          extensions:
            [submodule(recursiveSubmodules: true, reference: '')],
            userRemoteConfigs: [[url: 'file:///vagrant']]
        )

        // Build required containers
        sh 'docker-compose --file $WORKSPACE/sec-tests/zap-baseline/compose.yaml build'
      }
    }

    stage('zap-baseline-scan') {
      steps {
        // Run baseline ZAP scan against RailsGoat
        sh 'docker-compose --file $WORKSPACE/sec-tests/zap-baseline/compose.yaml up zap-scan-baseline'
      }
    }
  }
  
  post {
    always {
      // Copy the report from Docker volume to the workspace
      sh 'docker-compose --file $WORKSPACE/sec-tests/zap-baseline/compose.yaml up zap-copy-report-to-workspace'

      // Archive reports with the build
      archiveArtifacts artifacts: 'railsgoat-zap-baseline.html'

      // Clean up containers (remove containers and volumes)
      sh 'docker-compose --file $WORKSPACE/sec-tests/zap-baseline/compose.yaml down --volumes'
    }
  } 
}
